### ISSUE TITLE
Rate Limit Headers

### ISSUE THREAD

**Issue by b1naryth1ef** [b1naryth1ef/dscord#8]
https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/topics/RATE_LIMITS.md

**Comment by b1naryth1ef** [comment]
Done.

**Comment by Marqin** [comment]
It seems to not work properly.

When I'm writing to two different channels I'm getting two different Rate-Limits:

chan1:

```
{"X-RateLimit-Limit", "10"}, {"X-RateLimit-Remaining", "7"}, {"X-RateLimit-Reset", "1472742960"}
```

chan2:

```
{"X-RateLimit-Limit", "10"}, {"X-RateLimit-Remaining", "7"}, {"X-RateLimit-Reset", "1472742962"}
```

But this library seems to treat them like one Rate-Limit: https://github.com/b1naryth1ef/dscord/blob/master/src/dscord/api/client.d#L95 which can lead to abusing Discord API (we update our rate-limit with value from another channel that has higher value and then we write to chan where we had 0 and we trigger 429 :( ).

This should probably cache not `Route` but `CompiledRoute`.

**Comment by Marqin** [comment]
But this seems to not be a case for getting eg. Guild data.

Maybe it's because of  [`Bots have a per-channel and a global rate limit.`](https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/topics/OAUTH2.md).

So maybe Discord generally Rate-Limits for Route, but for channels it's CompiledRoute...

**Comment by Marqin** [comment]
Or maybe it's per /first/two/ parts of API url.
